php test-kickoff.php &
./test.pl BAILEY &
./test.pl BANGLE &
./test.pl BARKER &
./test.pl BARROW &
./test.pl BEAGLE &
./test.pl BEIGE &
./test.pl BILLOW &
./test.pl BOBCAT &
./test.pl BONSAI &
./test.pl BRONZE &
./test.pl CALICO &
./test.pl CAPER &
./test.pl CAUDEX &
./test.pl CHAMP &
./test.pl CLARET &
./test.pl COBRA &
./test.pl CONGER &
./test.pl CORNEA &
./test.pl CRAVAT &
./test.pl CURTSY &
./test.pl DAIKON &
./test.pl DAPPLE &
./test.pl DEWLAP &
./test.pl DIMPLE &
./test.pl DODGE &
./test.pl DOODLE &
./test.pl DRAKE &
./test.pl DRUID &
./test.pl DUNLIN &
./test.pl BAMBOO &
./test.pl BANTAM &
./test.pl BARLEY &
./test.pl BASALT &
./test.pl BEAKER &
./test.pl BELUGA &
./test.pl BIRDER &
./test.pl BODKIN &
./test.pl BOOMER &
./test.pl BUSHEL &
./test.pl CANARY &
./test.pl CARBON &
./test.pl CELLO &
./test.pl CHASM &
./test.pl CLERIC &
./test.pl CODEX &
./test.pl CONSUL &
./test.pl COUGAR &
./test.pl CRUMB &
./test.pl CYGNET &
./test.pl DAMSON &
./test.pl DELTA &
./test.pl DIADEM &
./test.pl DINKY &
./test.pl DOBBIN &
./test.pl DOGLEG &
./test.pl DOWSER &
./test.pl DRIVER &
./test.pl DRYAD &
./test.pl DYNAMO &
./test.pl BABOON &
./test.pl BANDIT &
./test.pl BARBER &
./test.pl BARQUE &
./test.pl BAWBEE &
./test.pl BEEPER &
./test.pl BIKINI &
./test.pl BISQUE &
./test.pl BONOBO &
./test.pl BOWLER &
./test.pl CABAL &
./test.pl CANTOR &
./test.pl CASBAH &
./test.pl CESIUM &
./test.pl CHROME &
./test.pl COBALT &
./test.pl CONCH &
./test.pl CORGI &
./test.pl COUPE &
./test.pl CUMIN &
./test.pl DAHLIA &
./test.pl DANDY &
./test.pl DEUCE &
./test.pl DIGGER &
./test.pl DIPPER &
./test.pl DOCKER &
./test.pl DOMINO &
./test.pl DRAGON &
./test.pl DROVER &
./test.pl DUGONG &

